name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image (Production Stage)
        run: |
          docker build --target production -t intothefathom/splyce-solana-frontend-app:${{ github.sha }} .
          docker tag intothefathom/splyce-solana-frontend-app:${{ github.sha }} intothefathom/splyce-solana-frontend-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push intothefathom/splyce-solana-frontend-app:${{ github.sha }}
          docker push intothefathom/splyce-solana-frontend-app:latest

      - name: Set Argo CD secrets
        id: set-secrets
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            {
              echo "ARGOCD_API_URL=${{ secrets.ARGOCD_API_URL_PROD }}"
              echo "ARGOCD_AUTH_TOKEN=${{ secrets.ARGOCD_AUTH_TOKEN_PROD }}"
            } >> "$GITHUB_OUTPUT"
          else
            {
              echo "ARGOCD_API_URL=${{ secrets.ARGOCD_API_URL_DEV }}"
              echo "ARGOCD_AUTH_TOKEN=${{ secrets.ARGOCD_AUTH_TOKEN_DEV }}"
            } >> "$GITHUB_OUTPUT"
          fi

      - name: Sync Argo CD and wait for completion
        run: |
          docker run --rm \
            -e ARGOCD_AUTH_TOKEN=${{ steps.set-secrets.outputs.ARGOCD_AUTH_TOKEN }} \
            argoproj/argocd:v2.4.3 \
            /bin/sh -c \
            "argocd app set splyce-solana-frontend-app \
            --server ${{ steps.set-secrets.outputs.ARGOCD_API_URL }} \
            --parameter image.tag=${{ github.sha }} && \
            argocd app sync splyce-solana-frontend-app \
            --server ${{ steps.set-secrets.outputs.ARGOCD_API_URL }} \
            --grpc-web \
            --timeout 180"