name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.pull_request.base.ref != '' && github.event.pull_request.base.ref || github.ref_name || 'dev' }}

    steps:
      - name: Set ENV_TAG
        run: |
          if [ "${{ env.BRANCH_NAME }}" == "master" ]; then
            echo "ENV_TAG=" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV_TAG=dev-" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_ENV=dev" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Run in bash
        shell: bash
        run: |
          echo "Branch name: ${{ env.BRANCH_NAME }}"
          echo "ENV_TAG: ${{ env.ENV_TAG }}"

      - name: Set secrets
        id: set-secrets
        shell: bash
        run: |
          if [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
            {
              echo "IMAGE_REPOSITORY=${{ vars.IMAGE_REPOSITORY_PROD }}"
              echo "ARGOCD_APP_NAME=${{ vars.ARGOCD_APP_NAME_PROD }}"
              echo "ARGOCD_API_URL=${{ secrets.ARGOCD_API_URL_PROD }}"
              echo "ARGOCD_AUTH_TOKEN=${{ secrets.ARGOCD_AUTH_TOKEN_PROD }}"
            } >> "$GITHUB_OUTPUT"
          else
            {
              echo "IMAGE_REPOSITORY=${{ vars.IMAGE_REPOSITORY_DEV }}"
              echo "ARGOCD_APP_NAME=${{ vars.ARGOCD_APP_NAME_DEV }}"
              echo "ARGOCD_API_URL=${{ secrets.ARGOCD_API_URL_DEV }}"
              echo "ARGOCD_AUTH_TOKEN=${{ secrets.ARGOCD_AUTH_TOKEN_DEV }}"
            } >> "$GITHUB_OUTPUT"
          fi

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image (Production Stage)
        run: |
          docker build --target production \
            --build-arg NEXT_PUBLIC_MOON_PAY_KEY=secrets.NEXT_PUBLIC_MOON_PAY_KEY \
            --build-arg NEXT_PUBLIC_WALLET_CONNECT_PJ_ID=secrets.NEXT_PUBLIC_WALLET_CONNECT_PJ_ID \
            --build-arg PROD_RPC_KEY_HELIUM=secrets.PROD_RPC_KEY_HELIUM \
            --build-arg NEXT_PUBLIC_ENV=env.NEXT_PUBLIC_ENV \
            -t ${{ steps.set-secrets.outputs.IMAGE_REPOSITORY }}:${{ github.sha }} .
          docker tag ${{ steps.set-secrets.outputs.IMAGE_REPOSITORY }}:${{ github.sha }} ${{ steps.set-secrets.outputs.IMAGE_REPOSITORY }}:${{ env.ENV_TAG }}latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ steps.set-secrets.outputs.IMAGE_REPOSITORY }}:${{ github.sha }}
          docker push ${{ steps.set-secrets.outputs.IMAGE_REPOSITORY }}:${{ env.ENV_TAG }}latest

      - name: Sync Argo CD and wait for completion
        run: |
          docker run --rm \
            -e ARGOCD_AUTH_TOKEN=${{ steps.set-secrets.outputs.ARGOCD_AUTH_TOKEN }} \
            argoproj/argocd:v2.6.15 \
            /bin/sh -c \
            "argocd app set ${{ steps.set-secrets.outputs.ARGOCD_APP_NAME }} \
            --server ${{ steps.set-secrets.outputs.ARGOCD_API_URL }} \
            --grpc-web \
            --parameter image.tag=${{ github.sha }} && \
            argocd app wait ${{ steps.set-secrets.outputs.ARGOCD_APP_NAME }} \
            --server ${{ steps.set-secrets.outputs.ARGOCD_API_URL }} \
            --grpc-web \
            --operation && \
            argocd app sync ${{ steps.set-secrets.outputs.ARGOCD_APP_NAME }} \
            --server ${{ steps.set-secrets.outputs.ARGOCD_API_URL }} \
            --grpc-web \
            --timeout 180"
